### PR TITLE
121 bug mining txs

### LINKED ISSUE #119: Wallet total doesn't update on receipt of new transaction.
## Operation System
Windows 10

## Expected Behavior
I should receive coins and the wallet update that information in my wallet balance.

## Current Behavior
The wallet identifies the new transaction, but does not update my TKL totals throughout the app. I am required to logout and log back in for it to update my balance.

## Steps to Reproduce
Send funds to an empty address and note that it does not update the TKL totals.

https://i.gyazo.com/e87a601f1df0100a863f3a640af0a947.png

https://i.gyazo.com/e982e61629f8373e6e161639bac215a0.png

### LINKED ISSUE #121: Incoming mining transactions are shown as Sent
## Operation System

MacOS

## Expected Behavior

Incoming mining transactions are shown as Received

## Current Behavior

Incoming mining transactions are shown as Sent

### PR DESCRIPTION
**Pull request by piggydoughnut**
Closes #121 
Closes #119

### CODE REVIEW

File: src/util/helpers.ts [hunk 1]
```diff
@@ -33,18 +33,18 @@ export const limitLength = (value: string, len: number) => value.substr(0, len);
 
 export const isAddressValid = (address: string) => /^[a-km-zA-HJ-NP-Z1-9]{26,35}$/.test(address);
 
-export const parseSenderAddresses = sender => {
-  if (!sender.length) {
+export const parseAddresses = address => {
```
Comment (acnebs) [inline src/util/helpers.ts:36]: This should probably be called `addresses`. And potentially a better function name would be `serializeAddresses` or `stringifyAddresses` or something.

Comment (acnebs) [reply src/util/helpers.ts:36]: Parsing usually goes in the other direction.

**Review by acnebs — CHANGES_REQUESTED** [review]

**Review by acnebs — APPROVED** [review]
